version: '3.8'

services:
  db:
    image: postgres:${DB_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  evendemy:
    image: node:latest
    restart: unless-stopped
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: 
      - /bin/bash
      - -c 
      - |
        cd /usr/src
        npm run start
    env_file:
      - .env
    ports:
      - "${EVENDEMY_PORT}:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/
      - /usr/src/backend/node_modules