name: Linting for evendemy

on: 
    push:
        branches:
            - gh-actions-ci-workflows

jobs: 
    unit-tests-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3